name: 'NRF Connect SDK CI action'
description: 'Building nrf connect sdk projects'
branding:
  color: blue
  icon: Link
inputs:
  board:  # id of input
    description: 'Board for build'
    required: true
  build_dir:
    description: 'Building directory'
    required: true
    default: 'build'
  add_flags:
    description: 'Additional flags'
    required: true
    default: '--no-sysbuild'
runs:
  using: 'docker'
  image: 'docker://ghcr.io/Hall-Lab-UMD/nrf-connect-sdk-ci:v3.2.1'
  args:
    - west 
    - build
    - --build-dir 
    - ${{ inputs.build_dir }}
    - .
    - --pristine
    - --board 
    - ${{ inputs.board }}
    - ${{ inputs.add_flags }}
    
